# Generated by Django 4.2.2 on 2023-06-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_member_email_alter_member_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pay',
            field=models.BooleanField(default=True, verbose_name="To'ladi/To'lamadi"),
        ),
    ]
